"""add active column to scenario_responses

Revision ID: 352df4cada18
Revises: 9535e4c5190c
Create Date: 2026-03-23 15:17:03.795655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352df4cada18'
down_revision: Union[str, None] = '9535e4c5190c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario_responses', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_responses', 'active')
    # ### end Alembic commands ###
