"""add location_preference to users

Revision ID: ac4e174c3bea
Revises: 5eb8acac97be
Create Date: 2026-03-23 21:53:22.115468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4e174c3bea'
down_revision: Union[str, None] = '5eb8acac97be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_preference', sa.String(), server_default='same_city', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location_preference')
    # ### end Alembic commands ###
